### ISSUE TITLE
Where is Version 3 for Ember. 3.16? on EmberObserver?

### ISSUE THREAD

**Issue by Benjy1979** [yapplabs/ember-radio-button#104]
The link to Ember Observer seems not to have a version 3 for Ember 3.16+ as stated on the ReadMe.md. My radio buttons seem to have no labels now after updating to Ember 3.26

**Comment by Benjy1979** [comment]
I have closed this because after removing it and reinstalling 2.0.1 they reappeared.

**Comment by Gorzas** [comment]
I'm having the same issue. Version 3 doesn't appear in Ember Observer neither in NPM, it also there isn't a tag for version 3. Can we reopen this ticket?

**Comment by Benjy1979** [comment]
Hi, I fixed all woes by uninstalling "ember-radio-button" and installing "ember-radio-buttons" instead.

**Comment by Benjy1979** [comment]
Yes it is a different repository. I didn't bother even looking whether it's using Glimmer. Only that the projects runs and life can move forward. But of course feel free to keep this thread updated of alternative solutions!
