### ISSUE TITLE
Install with Ember CLI 2.3 fails

### ISSUE THREAD

**Issue by mphasize** [yapplabs/ember-radio-button#11]
You can still install this addon with `npm install --save-dev ember-radio-button` and it works like a charm, but recent changes in Ember CLI mean that a little update is needed for the addon install to work again.

Nice component! Thanks for making it public.

**Comment by raycohen** [comment]
Thanks for reporting. I'll check it out today

**Comment by raycohen** [comment]
https://github.com/ember-cli/ember-cli/pull/3854

**Comment by raycohen** [comment]
updated Readme: https://github.com/yapplabs/ember-radio-button/commit/54fce95bebbfa3bf2d86917559193fe8c9db00d7

**Comment by mphasize** [comment]
Nice!
