### ISSUE TITLE
Run loop buggy behaviour

### ISSUE THREAD

**Issue by Maze-fr** [yapplabs/ember-radio-button#12]
Hello,

I found a "non blocking" bug in the run loop (I guess it there). In fact, it blocked my UT... but I found a "work around" fix.
I describe it in the way I made it happen.

I build a model containing a boolean :
```javascript
var MyModel= DS.Model.extend(EmberValidations.Mixin, {
  switcher: DS.attr('boolean')
)};

MyModel.reopen({
  validations : {
    switcher: {
      inclusion: {
        in: ['true', 'false']
      }
    }
  }
});
```
I user my value on a radio button. A radio button can't have boolean values, that's why my validation uses strings.
All this works, the type changes between boolean and string on the need and the validation works fine. And the REST part in Java gets the boolean value.

My problem is when I submit my page with no error.
If eveything is fine, I do a forward to another page (a list of MyModels). Then, after some seconds, I have an error in the consol :
```javascript
TypeError: this.$(...) is undefined
```
Following the error, it happens in this part of generated code :
```javascript
 _updateElementValue: (function () {
    Ember['default'].run.next(this, function () {
        this.$().prop("checked", this.get("htmlChecked"));
    });
}).observes("htmlChecked")
```
I use more than one radio button, but the only one making the error is the "true / false" one.

The "work around" fix I use is to define my property as string and not boolean. Everything works fine all the same, and I don't have the error anymore.

That's all, folks !

**Comment by Maze-fr** [comment]
I reproduced the problem in another way.
This time, it's not only "true / false" radio button, but all the radio buttons that trigger the problem.

In my workflow, I create a new record from an existing one (still same pages as below).
So, here is what I do :

> list page -> detail page (of one record) -> click to duplicate -> foward to creation page, filling the new model with the other's values -> fill what's left in the form -> submit the form -> go back to the list

When I do that manualy, it works, no problem.
But when I do that in my UT, as it is automated, it submits the form when "run.next" is still not performed, and I have the error.

Of course, all tests I do after "submit" are in a "andThen".
I guess it means qunit don't consider radio buttons "run.next" before to do what is in the "andThen".

PS : I managed to find a "fix" : I have to do something like that when I save my model :
```javascript
model.save().then(function () {
    Ember.run.next(...[uses a flashMessages to show success]
```
I wonder why radio buttons run loop is not finished when I save my model, as it has already been validated by ember-validations.

**Comment by raycohen** [comment]
Hi @Maze-fr - It sounds like you are using version 0.1.3 (or lower) of ember-radio-button.

We are now on version 1.0.5 and I think some of the changes we made could help with these issues. Are you using htmlbars?  If so, can you try it out with the newer code?

**Comment by Maze-fr** [comment]
As I checked the version, I noticed a HUGE misstake...
I use ember-radio-button**s**... I am so deeply sorry...

**Comment by raycohen** [comment]
No problem :)
