### ISSUE TITLE
Ember 1.13 beta issue? Block template generating inline template's output

### ISSUE THREAD

**Issue by ericestes** [yapplabs/ember-radio-button#15]
Found this after upgrading from 1.12 to 1.13-beta.2. Basically, 

{{#radio-button
    value="blue"
    groupValue=color
    changed="colorChanged"}}
    Blue
{{/radio-button}}

seems to be outputting the same html as

{{radio-button
    value="green"
    groupValue=color
    changed="colorChanged"}}

**Comment by raycohen** [comment]
Thanks for reporting.  I'll investigate.

In the mean-time, you can use the `labeled-radio-button` component provided by this addon (but not currently documented) in places you were using the block form of `radio-button`.

https://github.com/yapplabs/ember-radio-button/blob/master/addon/components/labeled-radio-button.js

It is re-exported into the `app` tree and should be usable with no other changes than adding `labeled-` to the front of your `{{#radio-button` invocations.

Please report back if that approach is successful.

**Comment by ericestes** [comment]
Yes, using `labeled-radio-button` worked fine.

**Comment by raycohen** [comment]
Ok.  I'm leaving this issue open while I investigate if the overloaded behavior of `radio-button` is still viable with ember 1.13+

**Comment by raycohen** [comment]
Some jsbins that help demonstrate the behavior change

Changing layoutName when component is used as a block in ember 1.12
http://emberjs.jsbin.com/zihixaqaxo/2/edit?html,css,js,output

beta (1.13)
http://emberjs.jsbin.com/zihixaqaxo/3/edit?html,css,js,output

**Comment by raycohen** [comment]
https://github.com/emberjs/ember.js/issues/11301

**Comment by jerel** [comment]
What is the status of this issue? I see that the related Ember issue had a merge and `{{#radio-button}}` works fine in my v1.13.2 app. However I'm getting deprecation notices from the addon: `Accessing 'template' in <my-app@component:radio-button::ember777> is deprecated. To determine if a block was specified...`

**Comment by btecu** [comment]
There is now `hasBlock` that can be used instead of `template`.

**Comment by raycohen** [comment]
There will be an update using `hasBlock` soon, but if you want to get rid of deprecations right now you can use `{{#labeled-radio-button}}` in place of `{{#radio-button}}`

**Comment by jerel** [comment]
`{{radio-button}}` is where the problem code actually lies and the `{{#labeled-radio-button}}` template calls `{{radio-button}}` so switching doesn't fix the issue. Using `{{#radio-button}}` generates twice the deprecation notices because it calls `this.get('template')` internally and also uses `templates/components/labeled-radio-button` :)

I worked on a fix for a bit but it's not obvious to me how to overload since `hasBlock` only exists in template land and is not available in js.

**Comment by btecu** [comment]
Yes, I switched to `{{labeled-radio-button}}` and I still get the same deprecation.

**Comment by raycohen** [comment]
sorry about that.  version 1.0.6, just released, switches to `hasBlock` which should no longer give any deprecations.  Please try it out and let me know if there are any issues!
