### ISSUE TITLE
How to Add My own class to {{radio-button}}

### ISSUE THREAD

**Issue by jordanblink** [yapplabs/ember-radio-button#24]
Hi I am trying to add my own class for styling as 
 `{{radio-button name="policyControl" class="link-radio" value=true groupValue=brand.ispolicycontrol changed="policyControlChanged"}}`
However the styles don't get reflected in the template..what am I doing wrong?

> There are things I regret, you cant forgive.. you can't forget ...

**Comment by raycohen** [comment]
In version 1.0.7 we added a `radioClass` property that allows you to specify any classes you want to show up on the input tag.

**Comment by raycohen** [comment]
So make sure you have 1.0.7 and try this:
```
{{radio-button name="policyControl" radioClass="link-radio" value=true groupValue=brand.ispolicycontrol changed="policyControlChanged"}}
```
let me know if it works for you

**Comment by lukemelia** [comment]
Silence suggests this is resolved. Please reopen if necessary.
