### ISSUE TITLE
Assertion Failed: You must pass exactly one argument to the if helper

### ISSUE THREAD

**Issue by michalhartwich** [yapplabs/ember-radio-button#26]
I'm getting the following error `Assertion Failed: You must pass exactly one argument to the if helper` when I use this example:
```
{{#radio-button
    value="blue"
    groupValue=color
    changed="colorChanged"}}
    Blue
{{/radio-button}}
```
Component without block works fine.

Versions:
```
Ember: 1.8.1
Handlebars: 1.3.0
jQuery: 1.11.3
```

**Comment by raycohen** [comment]
Are you using ember-radio-button version `0.1.3` ? That was the last version that supported ember without HTMLBars.  I'm not certain that 0.1.3 supports ember 1.8.1, but it might.
