### ISSUE TITLE
action on click?

### ISSUE THREAD

**Issue by thejase** [yapplabs/ember-radio-button#30]
Forgive the ignorance if this is a simple misunderstanding, but how can we attack an action to the label's click?  For my needs, `changed` can be triggered both programatically and with other keyboard methods.  I'd like click to fire a bit differently.

**Comment by raycohen** [comment]
I think you could create your own component that extends the `labeled-radio-button` component, and add a `click()` method to your subclass, and do what you want from there.  Does that cover your needs?

**Comment by thejase** [comment]
Thank you. That is a great suggestion, and will definitely cover my needs.
