### ISSUE TITLE
Cannot set groupValue manually

### ISSUE THREAD

**Issue by solex16** [yapplabs/ember-radio-button#31]
Use case is I want to reset my radio button's checked status after a user changes it because the form validation fails..
```
{{radio-button
      value="right"
      groupValue=direction
      changed="changeDirection"
}}

{{radio-button
      value="left"
      groupValue=direction
      changed="changeDirection"
}}
```

So direction is originally set to 'right', user changes it to 'left'..
In my changeDirection action the change fails validation, so I execute
`this.set('direction', 'right');`
but this fails to check the 'right' button, as expected?

I notice that if I don't have the changed action on the component, then it works fine.. I can set 'direction' OK..

**Comment by raycohen** [comment]
I attempted to make a reproduction of this in the test app and the reset button worked as I expected.  Can you share any more about your situation that might be relevant?

Here is my attempted reproduction code:

component
```
import Ember from 'ember';

export default Ember.Component.extend({
  direction: 'right',

  actions: {
    resetForm() {
      this.set('direction', 'right');
    },

    changeDirection() {
      console.log('changed direction');
    }
  }
});
```
template
```
<h3>Reset example</h3>
<div>
  {{radio-button
      value="right"
      groupValue=direction
      changed="changeDirection"}}
  Right
</div>
<div>
  {{radio-button
      value="left"
      groupValue=direction
      changed="changeDirection"}}
    Left
</div>
<div>
  <button {{action 'resetForm'}}> Reset Form</button>
</div>
```

**Comment by solex16** [comment]
OK, thanks for that feedback..
I think problem might be more to do with the 
`<label for="rightDirection">` 
where I have
`id="rightDirection" `
set on the radio button..
I have fixed by doing
`this.set('direction', 'right');`
as well as
`$('#rightDirection').prop('checked', true);`

ie I have to set both in Ember and JQuery, whereas if I don't have changed action I can get away with setting just the Ember object OR the JQuery property..

**Comment by raycohen** [comment]
I'm not sure I fully follow what the situation you're encountering is.  If you feel there's something that we can add to this library to help, happy to continue discussing
