### ISSUE TITLE
Should there be a 'for' attribute?

### ISSUE THREAD

**Issue by sheriffderek** [yapplabs/ember-radio-button#33]
It seems like the label should have it's `for` attribute generated as the input id is.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

Any thoughts on that?

**Comment by raycohen** [comment]
even though the readme doesn't show it, we did add this in https://github.com/yapplabs/ember-radio-button/pull/22

**Comment by raycohen** [comment]
you need to specify a `radioId` to get that behavior. that value will be used for the label's `for` attribute and the input's `id` attribute

**Comment by sheriffderek** [comment]
Ah ha. Sorry for the duplicate!

**Comment by raycohen** [comment]
No problem.  I will add better documentation for that feature
