### ISSUE TITLE
How set initial value during render

### ISSUE THREAD

**Issue by haldiggs** [yapplabs/ember-radio-button#35]
I'm simply drawing button in an {{each}} and I'd like to set checked. 

if groupValue=color then I had assumed if I draw all the buttons with groupValue="3" then the item with the value eq 3 would be checked, but does not seem to be the case.

**Comment by haldiggs** [comment]
Still hoping for an answer on this please...

**Comment by raycohen** [comment]
Your expectation sounds correct so I'm not sure what the disconnect is.

If you checkout this repo and run `ember server` you can interact with the [examples](https://github.com/yapplabs/ember-radio-button/tree/master/tests/dummy/app/templates/examples) and maybe get an idea of what is going on for you.

If you can provide code snippets or anything else that might help me diagnose I'll give it a look.

**Comment by jdhines** [comment]
For me, I have to set the `value` property statically (to whatever value that option should have), and then as long as the property I give to `groupValue` can match the `value` then that option gets checked.

```
{{#radio-button
        value=1
        groupValue=model.myProp
        classNames="btn btn-default"}}
        First Option
      {{/radio-button}}
```

**Comment by gauthierm** [comment]
I am having the same problem. I have a static `value` and a dynamic `groupValue` but no radio buttons are checked on rendering the template.

**Comment by gauthierm** [comment]
Okay, my issue was because my project was using https://github.com/Blooie/ember-radio-buttons which is an entirely different but similarly named ember addon. Disregard my above comment and if you are having the same problem, double check to see what addon you are using.

**Comment by ChrizzDF** [comment]
Hi guys 😃
I fell into the same problem and I solved it using [`ember-promise-helpers`](https://github.com/fivetanley/ember-promise-helpers), so in my template:
```
...
groupValue=(await ingredients)
...
```

Maybe it's helpful for anyone of you! 😎
