### ISSUE TITLE
Error: You cannot use `attributeBindings` on a tag-less component

### ISSUE THREAD

**Issue by twbrandt** [yapplabs/ember-radio-button#47]
After I upgraded from Ember 2.3.1 to 2.9.1, Ember throws the following error whenever a template using the `radio-button` component renders:

````
Error: Assertion Failed: You cannot use `attributeBindings` on a tag-less component
````

This addon is unusable in 2.9.1 because of this.

**Comment by raycohen** [comment]
thanks for reporting @twbrandt -  I will look into it

**Comment by raycohen** [comment]
@twbrandt Can you try upgrading to ember-radio-button to version 1.0.7 (the latest release) and see if this still happens?

We made a change to the way we were using `attributeBindings` a couple releases ago and I think if you're on the latest version it won't raise that error anymore.  Let me know, thanks!

**Comment by twbrandt** [comment]
@raycohen It still happens on 1.0.7.

**Comment by twbrandt** [comment]
@raycohen: a thousand apologies - this is my problem, not yours. I am using [data-test-selectors](https://dockyard.com/blog/2015/09/25/ember-best-practices-acceptance-tests) in my components. I have some code which reopens `Ember.Component` which adds `attributeBindings` for `data-test-selector`. This is the source of the error I am seeing. Closing this issue.
