### ISSUE TITLE
Why click instead of "change" event?

### ISSUE THREAD

**Issue by toranb** [yapplabs/ember-radio-button#6]
I noticed in the component you handle a "click" event but hacking around with my own component for this revealed that you *could* also listen to the change event.

I'm just curious why the team at yapp went with click (ie- is a cross browser thing / mobile browser thing / or just the right thing for the radio button input) ?

Thanks for an awesome OSS project team!

**Comment by raycohen** [comment]
Hey @toranb.  I took a shot at restructuring this to use the change event.

If you have a chance, I'd like your feedback on https://github.com/yapplabs/ember-radio-button/pull/7?

Thanks!

**Comment by toranb** [comment]
Awesome! I was still curious about the question I asked above (ie- why click over change / what should people be doing with the radio button if they are forced to implement it outside of this project for whatever reason) ?

Thanks for the great OSS contributions ! Can't wait to see these merged in!

**Comment by raycohen** [comment]
1.0.0 now responds to the `change` event
