### ISSUE TITLE
groupValue not updated on button deselect

### ISSUE THREAD

**Issue by robertsteilberg** [yapplabs/ember-radio-button#60]
To me, It seems like a critical flaw in this addon is that the groupValue of a radio button is not changed back if it is deselected. For example, if I select radio button A, it's `groupValue` will become `value`, but if I think select radio button B, its `groupValue` will also become `value`. Then, both radio buttons A and B have `groupValue === value`, which means that I can't determine what the user actually wanted to select when I go to validate the form on submit. This violates the basic premise of having radio buttons in the first place.

**Comment by raycohen** [comment]
`value` is expected to be provided differently on each `radio-button` component. Therefore if valueA and valueB are different, you can't have both match the `groupValue`. Maybe this is a documentation issue or a naming issue?

**Comment by robertsteilberg** [comment]
In the context of my issue, every radio button represents an object, and selecting a radio button will set `field===true` in the corresponding object. Ideally, after the user submits the form, I can iterate through these objects, find the one with `field===true`, and do with it what I want.

**Comment by raycohen** [comment]
if you're able to make a pull request that adds a simple example to the dummy app inside the addon (like these examples https://github.com/yapplabs/ember-radio-button/blob/master/tests/dummy/app/templates/index.hbs) that would help me diagnose. I can look into this more over the weekend. It sounds like usage that we intend to facilitate.

**Comment by raycohen** [comment]
I've opened a PR with an example showing passing objects to the `value` and `groupValue` and seeing the behavior I expect. Let me know if this matches the use case you were describing:

https://github.com/yapplabs/ember-radio-button/pull/61

**Comment by robertsteilberg** [comment]
I think I was misunderstanding how to use the addon. I see now that the value of `selectedColorObject` will indicate which object was ultimately selected by the user. Though it's my own fault for overlooking the assumption that `value` is expected to differ among each invocation of the component (which in hindsight is glaringly obvious) it may be a good idea to make a note of this on the README.

**Comment by raycohen** [comment]
closing as we've given the README an overhaul
