### ISSUE TITLE
Allow specifying a label using inline invocation

### ISSUE THREAD

**Issue by myartsev** [yapplabs/ember-radio-button#64]
Currently, it is not possible to specify a label using inline invocation.

```javascript
{{radio-button
    value="green"
    groupValue=color
    changed="colorChanged"}}

{{#radio-button
    value="blue"
    groupValue=color
    changed="colorChanged"}}
    Blue
{{/radio-button}}
```

What do you think about adding a _label_ attribute? Or if none is specified using the _value_ attribute as the label? Perhaps I am not seeing the use case, but I haven't come across a need for a label-less radio button.
```javascript
{{radio-button value="green" label="Green" groupValue=color changed="colorChanged"}}
```

**Comment by raycohen** [comment]
why doesn't using the block form suit your needs?

**Comment by myartsev** [comment]
The block form does of course work; but does anyone use the inline form as it is currently? Just seems incomplete.

```
A link in {{#link-to "index"}}Block Expression Form{{/link-to}},
and a link in {{link-to "Inline Form" "index"}}.
```

**Comment by raycohen** [comment]
the inline form is provided for use cases where more control is needed. it intentionally does less than the block form
