### ISSUE TITLE
CRUD : Edit does not retain previous value

### ISSUE THREAD

**Issue by Paskalouis** [yapplabs/ember-radio-button#65]
Hi All,

On my app, I have Create, which function normally. It saves value to my database.

Then on edit, the radio button of the same value is not 'checked'.
I want to add attr checked="checked" on initial state, but it seems nothing changed.

Thank you

EDIT : Or this issue may equal to, 'How to make radio button checked by Jquery manually ? Because it adding checked attribute does not change anything'

**Comment by 85636682** [comment]
i have the same problem

**Comment by raycohen** [comment]
an ember radio button will be in a checked state when the `value` and `groupValue` props are equal. Manually setting the checked attribute after the component mounts with jquery or some other method is not supported.
