### ISSUE TITLE
Publish new version ;)

### ISSUE THREAD

**Issue by knownasilya** [yapplabs/ember-radio-button#8]
Would love if you could publish a version with the new required features :smile:

**Comment by raycohen** [comment]
We've got some significant changes going on in a branch (with an open PR).  A little hesitant to release more versions until we've decided what direction we're going with that PR.  We'd welcome your feedback on #7

**Comment by knownasilya** [comment]
Looks like those changes would require a major version bump, is that correct?

**Comment by raycohen** [comment]
I just published version 0.1.3

You're right, the changes in that PR will move us to a new major version.

**Comment by stefanpenner** [comment]
:+1:
