### ISSUE TITLE
Question: What is this syntax in render of a test

### ISSUE THREAD

**Issue by bgantzler** [yapplabs/ember-radio-button#80]
I saw this syntax in the radio-button-test. What does the tilde do?
```
this.render(hbs`
    {{#radio-button
        groupValue=groupValue
        value=value
        checkedClass="active"
        changed='changed'
        classNames='blue-radio'
    ~}}
      Blue
    {{~/radio-button}}
  `);
```

**Comment by raycohen** [comment]
I believe they remove whitespace, such that the text node contains "Blue" and not something like  "\n   Blue\n  "

**Comment by raycohen** [comment]
See "whitespace control" http://handlebarsjs.com/expressions.html

**Comment by bgantzler** [comment]
I cant believe I didn't know about this. Seems like something that should be used more often.

Thanks
