### ISSUE TITLE
Replace sendAction with closure actions

### ISSUE THREAD

**Issue by Sinled** [yapplabs/ember-radio-button#85]
In latest ember (3.4+)
using `sendAction` results deprecation warning [[deprecation id: ember-component.send-action]](https://github.com/emberjs/rfcs/blob/master/text/0335-deprecate-send-action.md)

**Comment by injaon** [comment]
This would be very useful. +1

**Comment by BillyRayPreachersSon** [comment]
We're also seeing a lot of these in our application since upgrading to 3.4 LTS.

Would updating to use closure action and revving to 2.0.0 be a workaround for those still on Ember < 1.13 to avoid a breaking change?

**Comment by benkiefer** [comment]
Any update on this? Thanks for all the work on this.

**Comment by aandis** [comment]
+1

**Comment by raycohen** [comment]
update merged, release forthcoming. thanks to @tomoguisuru

**Comment by benkiefer** [comment]
Any update on when the release might be?

**Comment by raycohen** [comment]
Version 1.3.0 is released and includes support for _passing_ a closure action to a `radio-button` - see examples in the updated README.

Version 1.3.0 does _not remove sendAction deprecation warnings_ because it still uses `sendAction` internally, even when a user passes a closure action.

**Comment by benkiefer** [comment]
Any chance we can get a 2.0 that kills the deprecation warnings too?

**Comment by raycohen** [comment]
version 2.0 [has been released](https://www.npmjs.com/package/ember-radio-button)
